[tools]
python = ["3.14", "3.13", "3.12", "3.9", "3.10"]
usage = "latest"
terraform = "latest"
node = ["latest", "lts"]
dive = "latest"
fzf = "latest"
golang = 'latest'
kubectl = "1.27"
opentofu = "1.7"
ruby = "2"
